APP_NAME = "Dirt Tracker"
VERSION = "0.1"

MODE_RIDE = "ride"
MODE_CIRCUIT = "circuit"
MODE_ENDURO = "enduro"
MODE_ENDURO_TIMEKEEPING = "enduro-timekeeping"

SCREEN_WIDTH = 128
SCREEN_HEIGHT = 64

UNITS_ENGLISH = 1
UNITS_METRIC = 2

WHEEL_SIZE_MINUMUM = 16.0
WHEEL_SIZE_MAXIMUM = 20.0
WHEEL_SIZE_INCREMENT = 0.2

SSID = "dirt-tracker"
